export enum AUTHENTICATION_STATUS {
  UNAUTHENTICATE = "UNAUTHENTICATE",
  AUTHENTICATED = "AUTHENTICATED",
  AUTHENTICATING = "AUTHENTICATING",
}

export enum LOGIN_STATUS {
  PROCESS_LOGIN = "PROCESS_LOGIN",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  IDLE = "IDLE",
}

export enum SIGNUP_STATUS {
  PROCESS_SIGNUP = "PROCESS_SIGNUP",
  SIGNUP_FAIL = "SIGNUP_FAIL",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
  IDLE = "IDLE",
}